/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package olc1.practica1_201700371;

import java.io.BufferedReader;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.FileReader;
import java.io.InputStreamReader;
import java.io.PrintWriter;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author mynor
 */
public class Intefaz extends javax.swing.JFrame {

    /**
     * Creates new form Intefaz
     */
    public Intefaz() {
        initComponents();
    }

    JFileChooser seleccionar = new JFileChooser();
    AnalizadorLexico analisis = new AnalizadorLexico();

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextPane2 = new javax.swing.JTextPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();

        jMenu1.setText("jMenu1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jScrollPane1.setViewportView(jTextPane1);

        jScrollPane2.setViewportView(jTextPane2);

        jMenu2.setText("Archivo");

        jMenuItem1.setText("Abrir");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem1);

        jMenuItem2.setText("Guardar");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem2);

        jMenuItem3.setText("Guardar como...");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem3);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Analisis");

        jMenu4.setText("Analizar");
        jMenu4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu4ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenu4);

        jMenuItem4.setText("XML de salida");
        jMenu3.add(jMenuItem4);

        jMenuItem5.setText("Analizar");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem5);

        jMenuItem6.setText("Locura");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem6);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 675, Short.MAX_VALUE)
                    .addComponent(jScrollPane2))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 401, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 10, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    FileOutputStream salida;
    JFileChooser elegir;
    FileOutputStream out;
    File documento;
    PrintWriter wr;

    public String GuardarArchivo(File archivo, String documento) {
        String mensaje = null;
        try {
            salida = new FileOutputStream(archivo);
            byte[] bytxt = documento.getBytes();
            salida.write(bytxt);
            mensaje = "Archivo Guardado";

        } catch (Exception e) {

        }
        return mensaje;
    }


    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        try {
            JFileChooser abrir = new JFileChooser();
            String cadena = "", texto = "", direcion = "";
            abrir.setFileSelectionMode(JFileChooser.FILES_ONLY);
            FileNameExtensionFilter filtro = new FileNameExtensionFilter("er", "er", "er");
            abrir.setFileFilter(filtro);

            try {
                int selecciona = abrir.showDialog(jTextPane1, "Abrir");
                String path = abrir.getSelectedFile().getParent() + "/" + abrir.getSelectedFile().getName();
                direcion = path;
                if (selecciona == JFileChooser.APPROVE_OPTION) {
                    try {
                        File archivo = new File(path);
                        FileReader lector = new FileReader(archivo);

                        BufferedReader leer = new BufferedReader(new InputStreamReader(new FileInputStream(path), "ISO-8859-1"));
                        String linea = "";
                        int lin = 00;
                        while ((linea = leer.readLine()) != null) {
                            cadena += linea + "\n";
                        }
                        leer.close();
                        cadena = cadena.replace("ï»¿", "");
                        cadena = cadena.replace("Â", "");
                        cadena = cadena.replace("", "");
                        cadena = cadena.replace("”", "\"");
                        cadena = cadena.replace("", "");
                        cadena = cadena.replace("Ã±", "ñ");
                        cadena = cadena.replace("Ã¡", "á");
                        cadena = cadena.replace("Ã³", "ó");

                        jTextPane1.setText(cadena);
                    } catch (Exception e) {

                    }
                }
            } catch (Exception ex) {
            }

            // lexer scani
        } catch (Exception ex) {

        }
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private String guardarComo(File archivo, String texto) {

        String mensaje = null;

        try {

            out = new FileOutputStream(archivo);
            byte[] bytxt = texto.getBytes();
            out.write(bytxt);
            mensaje = "Archivo Guardado";

        } catch (Exception e) {

            JOptionPane.showMessageDialog(null, e, "ERROR", JOptionPane.ERROR_MESSAGE);

        }
        return mensaje;
    }
     JFileChooser abrir;
   
    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        if (!jTextPane1.getText().equals("")) {

            if (seleccionar.showDialog(null, "Guardar") == JFileChooser.APPROVE_OPTION) {

                documento = seleccionar.getSelectedFile(); // selecciona el archivo

                if (documento.getName().endsWith("er")) {

                    String texto = jTextPane1.getText();
                    String mensaje = guardarComo(documento, texto);
                    if (mensaje != null) {

                        JOptionPane.showMessageDialog(null, mensaje);

                    } else {

                        JOptionPane.showMessageDialog(null, "Archivo no compatible");

                    }

                }

            }

        } else {

            JOptionPane.showMessageDialog(null, "Ingrese Texto", "ERROR", JOptionPane.ERROR_MESSAGE);

        }
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
                try {
            abrir = new JFileChooser();
            String cadena = "", texto = "", direcion = "";
            abrir.setFileSelectionMode(JFileChooser.FILES_ONLY);
            FileNameExtensionFilter filtro = new FileNameExtensionFilter("er", "er", "er");
            abrir.setFileFilter(filtro);

            try {
                int selecciona = abrir.showDialog(jTextPane1, "Abrir");
                String path = abrir.getSelectedFile().getParent() + "/" + abrir.getSelectedFile().getName();
                direcion = path;
                if (selecciona == JFileChooser.APPROVE_OPTION) {
                    try {
                        documento = new File(path);
                        FileReader lector = new FileReader(documento);

                        BufferedReader leer = new BufferedReader(new InputStreamReader(new FileInputStream(path), "ISO-8859-1"));
                        String linea = "";
                        int lin = 00;
                        while ((linea = leer.readLine()) != null) {
                            cadena += linea + "\n";
                        }
                        leer.close();
                        cadena = cadena.replace("ï»¿", "");
                        cadena = cadena.replace("Â", "");
                        cadena = cadena.replace("", "");
                        cadena = cadena.replace("”", "\"");
                        cadena = cadena.replace("", "");
                        cadena = cadena.replace("Ã±", "ñ");
                        cadena = cadena.replace("Ã¡", "á");
                        cadena = cadena.replace("Ã³", "ó");

                        jTextPane1.setText(cadena);
                    } catch (Exception e) {

                    }
                }
            } catch (Exception ex) {
            }

            // lexer scani
        } catch (Exception ex) {

        }
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenu4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu4ActionPerformed
        // TODO add your handling code here:
        
        analisis.analisis(jTextPane1.getText());
    }//GEN-LAST:event_jMenu4ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        // TODO add your handling code here:
        
        analisis.analisis(jTextPane1.getText());
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Intefaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Intefaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Intefaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Intefaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Intefaz().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextPane jTextPane1;
    public javax.swing.JTextPane jTextPane2;
    // End of variables declaration//GEN-END:variables
}
